# Generated by Django 4.2.5 on 2025-10-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='商品名')),
                ('price', models.IntegerField(verbose_name='価格')),
                ('image', models.CharField(max_length=255, verbose_name='商品画像URL')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
